/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "xfefnvhzuxqpopoyifpf"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhmZWZudmh6dXhxcG9wb3lpZnBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0Njk0OTgsImV4cCI6MjA3MzA0NTQ5OH0.8Ifvu6XbKF-NdwJf_6HKzgmo-V8u6-wLmnnMmCTiAvg"